apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: api
          imagePullPolicy: Never
          ports:
          - containerPort: 80
          env:
            - name: DATABASE_STRING
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: mysql-database-name
            - name: HOST_STRING
              valueFrom: 
                configMapKeyRef:
                  name: database-configmap
                  key: database_url
            - name: PASSWORD_STRING
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: mysql-admin-password
            - name: USER_STRING
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: mysql-admin-name
      # restartPolicy: Always
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: api-service
# spec:
#   selector:
#     app: api
#   ports:
#     - protocol: TCP
#       port: 80
#       targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    app: api
  type: LoadBalancer  
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30001
