version: '3.8'
services:
  client:
    build: ./client/
    # volumes:
    #   - ./:/app
    #   - /node_modules
    ports:
      - 8080:80
    container_name: client
    depends_on:
      - api
    networks:
      - frontend
  api:
    build: ./api
    # volumes:
    #   - ./server:/server
    #   - /server/node_modules
    # ports:
    #   - 3000:80
    environment:
      HOST_STRING: database
      DATABASE_STRING: ${DATABASE_STRING}
      USER_STRING: ${USER_STRING}
      PASSWORD_STRING: ${PASSWORD_STRING}
    container_name: api
    depends_on:
      - database
    networks:
      - frontend
      - backend

  database:
    image: mysql:8.3.0
    volumes:
      # persist database
      # - "db_data:/var/lib/mysql"
      # mount schema file
      - "./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql"
    container_name: database
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${DATABASE_STRING}
      MYSQL_USER: ${USER_STRING}
      MYSQL_PASSWORD: ${PASSWORD_STRING}
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD_STRING}
    networks:
      - backend
    restart: always

networks:
  frontend:
  backend:
