version: '3.8'
services:
  client:
    build: ./client/
    # volumes:
    #   - ./:/app
    #   - /node_modules
    ports:
      - 8080:80
      # - 5001:80
    container_name: client
    depends_on:
      - api
    links:
      - api
  api:
    build: ./api
    # volumes:
    #   - ./server:/server
    #   - /server/node_modules
    # ports:
    #   - 3000:80
    # - 3001:3001
    container_name: api
