version: '3.8'
services:
  client:
    image: client
    build: 
      context: ./client/
      dockerfile: Dockerfile
      args:
        API_URL: ${API_URL}
    ports:
      - 8080:80
    depends_on:
      - api
    networks:
      - frontend

  api:
    image: api
    build: ./api
    # ports:
    #   - 80:80
    environment:
      HOST_STRING: database
      DATABASE_STRING: ${DATABASE_STRING}
      USER_STRING: ${USER_STRING}
      PASSWORD_STRING: ${PASSWORD_STRING}
    depends_on:
      - database
    networks:
      - frontend
      - backend

  database:
    image: database
    build:
      context: ./database
      dockerfile: Dockerfile
      args:
        MYSQL_DATABASE: ${DATABASE_STRING}
    # ports:
    #   - 3306:3306
    environment:
      MYSQL_DATABASE: ${DATABASE_STRING}
      MYSQL_USER: ${USER_STRING}
      MYSQL_PASSWORD: ${PASSWORD_STRING}
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD_STRING}
    networks:
      - backend
    restart: always

networks:
  frontend:
  backend:
